title:              Song Space
email:              zuppiy@seoultech.co.ac
description:        A Blog
author:             Song Hyun Kim
baseurl:            ""
url:                "https://nxver.com"

# Social Profiles
twitter_username: 
github_username:    songk1992
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
